<?php @include('templates/header.php');

@include('codes/day-3.php');

$string = 'fBDGBcBrGDvjPtPtPV
QhzJLlLJZgLZzNTgZClQHvRvHFvrjrvnNjHnFjPF
ChldsCZhsQzsCGrrSfMfGpfrdM
MJbgcgJlvMSbfjMSbllmCrntwmFrrFwgtCtFFG
vPhddVZZhmnmdnHmHn
vNBZppZQhjSzfScjDN
jwhqbZRvbzvbqqpqzqHHCCCzsLmmQVtmJVJtLWLPrVLLVrmp
dGMfMGMdBBMSTfdMGTNlcZGGPSmQJVVWsJQPLmPLVPtmWPLW
llMBBcfBnBcZMGgqvCDbjbwgCHjvzH
RSDprRrwgVVRwrGqrJsNFJslgglmmNszzN
LLnWjcHWnCTmpClhHp
MpfMZWjtLMjpjtBPnLPndMBGRqwbwBwvrGwGrGVbVvwD
PQNGshQWtwWNcjssJHHJdlBLBlLrRDFFCrdwSlLB
mbzqZqsgMzfnbmbfgpZvZBLrLlSCrprDlLCrdFBlDL
MfvZzqMmsVnVzzTTbMzfvnctjhcHPQJJjNTGWjQJJHWP
MdLWQdMZrPQWsPdMQPLSqGpHGbGqpqqqVzpm
BhgFhVgnlgBNFtNwzpbTGbTTHpwwbF
tCfvvCfgvBjnfflftCvjWZVddMQZsMMsRdMZMP
lTLdHVlqmqWdvjvJttvFlJtC
ngbMTgGhQpgrGtvCzcCJccCrcj
npgwnDpSDbgbbnGGDQnMDSMgZZWVqNTNPRRdwLLNLqmPZTLP
RRSFZvRdrdbSvSVLRZrSGZZrHcHPfPPwJJVJmPHmJfHVThPm
WnLjBQBCQWqCQwpPmHTcfQpm
gBDttlnqLqlvzzlGRRlr
wGpdGdddMPDWgFJGBzmMlntTbZMtZbnT
qNSqQrrqSjQVrsvTtzNnnZTnfNztZw
rcVrjjsswVvRRHsFJLCDCpCddGCCcG
jLMhCPWLCSWSrRLPWmPPLSCLtcTvHHDhZcfHHltlfZtlfgfH
rBBNrbVdtZlvVcZc
FppGdpFsnsqGJnsFzGdJszbdwSLRSRPrSRjqrMqCwQMWQqRS
jTjZwnpjMDfZnmZfsRhGGztqCzwsdGws
JHrWcNrNNrJHLHlzsCtzGRRRHv
rNLrVBJFLmfCnbTpVQ
LGWJvDFssFmMBhThMvnB
CprbCNZpwfpwfrbZJMQMTQcVVgBZcVQBZc
ptNwfwzHzqzlttbrlpCCqzwtFLGSWFsPDLWFHSDjJWSDLFDs
MZJjSsCsMsZSSdZJhdjZtCbPHljqlLPlPRRDLqHHqLbB
mmwmVpGrnngmggGwnccPbDBPLLLllLBcFRFb
GQzVTQTTVzVrQrmvpTnmrQmMvZRhZZCZSZfCsfttSJddNC
gHZZQRdVgRQWWRPHWPnttDTmqQqDQnStzNqD
bscfjslJJspBLsslNStSmTmLmmDTzNnS
JJCrbbhBsplrrChpBbfjlpbbFWWVggPPhZVRRFPdVMddPnMg
FtLfHNhFJCClJlst
jnDQqnDSDSRqwBwnjdFlZbsrTZdsJsGCbw
zDFSmjSDVqnRMHmphPhfWPgW
rSpRtSPWpStVqrwSSdrrhZvnBBnDBvsqjlBqvvnnzl
LFNLLFfFFhMFbcbmbHbHgTNcvZvBZMsvBnJBzsZvjJvZlvnZ
gmFLhTTbFmmQrrSWWpwWVtwQ
DzmDJGSccGJPcdcJPJqwplhjBHmHVwwtBthV
grMMvRsNRnWCFrgZRrZFhpVVlHVnhpVjVtljhhhf
FFZFZTsvCMSQTdGcTHzT
TLsGTnZncjVmVLgm
DvRwMcHMvMbwBVlCBlzlMjCC
FdRtRHDwQvPnTfPqcFPP
rZNdpBSldLLCJZbbCT
WQcQwqsmQmmqJgTRLRCqLq
znQcwsmPcmnCzQmfGGnzHSDFlNptNthPSdllhFPplS
vWCWvVhhjPNjNNvWVNbnbHnrbGrmlPqnqqbw
JdZSLMgsdgQMcQssQnnDqmDqlDqnDlwrHc
tdgQSSdpQtSMSNWpWRfRCwjpjV
qhdJFpChSJhDFDrqbpJbddSHPPRnGGBfBrHfZRnjRnlBZH
zsMVzmwmtLMtmQTzvwlRcZnZZljvvfGcBjcZ
ttQzMtVgMWVMQsmtJgqJgCJbqhgbBSBN
BWvdCmZBrNRrGSSfTzQJJRTz
gMblllMgLVswbgwMsLjgLLnlVtfHfttSQttTJTSQGfGPTPTB
LMgnMgscgqbFBqvBNFBmNm
VlcczDZjjVbznwLnwpTH
NfJPJNfJdJMSHSHnjBRSnbbL
NddqPttjsdZDqhcqlFcD
NVrNBBFFFrvJJrVTFTNvWBCbCCgWGqDqhqghCLqbqtCC
mfZVPZPcqtLbcqgc
fwZlwzfRfQQPMZBBwwBjFSjTVrBT
GWWNMfWWwGWMtjJnVnJzlzVsvLnsVn
ZpRqHTBddsvtPLqVPP
bpSDgStgTbdFTpDdRmfwfmfGFcMQGWMcjQ
gCgGBgfCbRLbBLGnGBBfRGwprctZFMvtFtvSNNTZZtMvLc
DhJhDzzQlDdshVJlDdhqzqzQZFpppFMNtMZMtFFVvtpSMpFV
qQdsDHWWslnNgHmBbHBf
MRvnJFZVnvzJrWWSqMSPTSNqNj
GlcbDpCHCCczdsDppcccBGccqjwTTwQPPSjNjWSWSwwsPsws
GbdlBbgdVtngtzVg
GqTSRpgJgDNSNJqJlSTJlJCBmmcnjCjLFcMFmnGsmBsM
HPhfPrWdfrQPPPhQWHbLFFWFCmFjMBFFsLBFwj
fdzVbvfshrbzvfbfdVPvQtqqJgqgDpNTgqZZtglZtZDD
wsPhrDMfrwdvHdTFrrtH
lnQbNBbqVBqHGJSddvTlJJJJ
cjnHznzbQmgzqQjBWwZwRjDRfWWhWsWD
SsScnttbbSzRRMMMLpsBLP
dDJGgjGJVMSBBBMj
JGDNCfgfSChDJrgqdgqJqGbNbbcbNtzWFctbzzlWtFFn
dtsBsCMtwSVBlLZZZnMgcMZZ
brppQHGznLZgJzJJ
fprvRpNHpNnvbGDBCBPwBWFWBFBvtB
qjgjSgHNlSGHnjfSVDvDPRDDtcdDcGtD
FMTnnLQZtRZDbcZv
zhBLzrCwnCsTCMCQTFLwwCzpHgNlNmHqhlqSpWllmlllhh
bJqqFdfbGdfPNsJsdSRCFLRHLDDBHDnShL
lQWlWQpwQjlpwrjrwTSCTLMCCNTHRDDDDRRB
wtWgQmQQWtwWwrljNPfGPzJmbbfzmzZf
MjppbDGmNNblCpzsNZzhNPgHtzzs
qvdrqrQVVWLfqWfRRPRwZPPwggpf
cqdcdpqSrrSvrvWvvvrSbcGTTTbGlFFCCcnnGbTb
HLNfNGttHVFBHWSr
RZCLsbCbLbLhwzDgbZCbRZhhnpSnnWpWplFFnDnqlBFVpSVB
MzbhhzwcLGGfGMvMTv
PdBlpdVJlmftGbTzwbtRTGGL
NQNMgWNNQNScDhsSHSWhsNgbRCLwGnnwqLwLHbbCGGTjTR
MvhRMMRvQshgSNDWFrfBfJFZrFPJJJPBBp
qdtnQqWtnjfGGzsnGQmWWfqQNbRTgggRFNbCFNSSFlSJsrTr
PZBBbPMvVcMpSRSlSCpCSgCT
MvHZhwMVLDHDcZMvLQfwGWqwWjqjGbmnQq
NFPmjNhGthGNpddddFpzBbqPczSqPDzzDgbgLZ
VJWvwQrlLHWrvlQZDgZSSDSDBqbb
WfHwMWfvRvMWrWJsrfMRWGFmGGLttMNpjCpTdmFFht
DppfNpLwhTBRDbblgWNgCdgCvs
nLcLqFJrHJmLcFmqMFCdzdHdsgvdzvbvWPWs
nVFqrrQcSVmFjrmJnrFrSjTtRGRLBwfRTfZwhBQhRGGw
sHrZdHGpHhsrLpsssGLzhrdtWdJTMWJvffVdmnbfJVnW
cggRDCCjlPQCgDRnfbTtfMJfWVTm
cCDwQNlwQPjgCFDljwpSLFzGFzZhzsstSpGz
dGTGpGdPZZCpnnLRpgzgzn
lflshFjFcrNdBjMjMnmL
hDfrldDfbVPbQCtHHZ
cSRZmtFZScfjZtLbmCNMqhMVQCjwqqCwVB
pddczHpHHzgWdGdsvPrPzcvrJMNwJCQwJhNwBhCJBVMpCVJB
cgrWcHdnPHHznlmftmtLnRDD
PZFMMVJVZmVJVHMNJNVfNdNNSnSWsSRhgRRQnWSsRnSWmszc
llljlTwlprClTbTpwLlgQqhcnwnczhcgSqsQRR
TpCtGtrTBDZVZHNQZQdB
SggjglBBlzbDgdpFJddZpF
CCNLsfNfrcMLsTLPfPmndmTwmZtZJZJdJplp
sfWCqcvMrlMfMLsLNfhVGvjjjSzSzVQhQvVH
NTBhNhfBvfflsbSmcl
nrMZRnHHwBMZRsSsgSsGrbmdms
nPPFVwVWJqJBVJLT
vvWqWJWJvzfFZZJvWQzqZvdPPHjSfHjssHsbsfbjSHRR
DCwtDVjMCrltCnCrDCDmbTssPHLTLldssdSldSRp
nMcGtDmBmMGrGvvvvFhjFZgWcN
tGWWWfWpMDjMZbTbnqTC
JFscJzFPDJDJZnrJ
sBFPcBsSPBvmSPwFzSSQfpwWfDpgNNfWtfgpftfg
BvTsJJzQJLMlbhmbFlNmTl
PjGnpdpGcgDmhvnvmvlbmq
dRtDGGgcDtjRcwdgQLVLRMJsszJVLRQv
FGbPPfFSchBGSvGGWsjSTLVQLLVTsQlj
dDzPnCrRCrrWHHTTHsdVjs
wrwCgzMrNprCwRJJwnnbFmmpGZtcvcbFfPFmFG
fbrJjmmmZgmZLJZsBBWlCBGnCWdnfF
RVMDDNDHPNvvRvDtHMcctMqFslqWPnClddlClFlnBqCG
MDDvHzHVQMMDtTHJLrnggSZLTJZgTL
dgBBCBBdvbmrRczFMHMSrqjjSPzn
tZTwQlLVwnQLQQFJVPzjDSSzJFPD
fhWhQpTTZQlWfQWpWQWQLhBgchhRCsdbvNnbgRsmRR
LttflLnGrnMsmmHgWTbdMW
vBSWzZRDccWBFBmJsmPJmgbsgB
FppcFWRNRZLLppGrGrqr
JJClRmLlFGvMTlFLLfPFQQcDpQcjFcjqBc
zgHSZhggggtwSZhrDgsZgbjVQcVcjPNqcpQQqBjNQzNp
hZnsShSWGDMMMRnv
RbDbslClhsfNCbsMjbNrjNMfpTTTTJSzHTpLVzLLVWVzJz
ggFGgmqFZBnnSzTWPpHBLzdT
vmWZWGwcZZqthjDrbclNCjlD
dCHwnVBBCBnVHddqnQRdbbbrgTsfWwjcWlsfwDDg
hhlFpMtGJlZmDjfWfscjWDGD
hFNFvZmppmSlNJMmNFztmzFhdVPPHQQqqHPvLBQnBQQPQPnC
WfzsplQpvQgfwzlbllPGtPJTTwtGGZBTTGJB
VrmMjmFDjNjjDFBhHTcZtBRRGcGV
mqrFmmLrjmjZnmqLrmQsfvbsfsSSlpWqgglp
lsQVfDpfflpGGmQRRgdQbdfbWdqnjnHnqZHJTqqrWjqqcWnZ
PPFhFFtwzqjHgjWTWF
SwMwMhNMlMsgfQfl
cSttSDQQCgVvQQSvsstthQcslLLgLgLnpglffjfFlLFblnlH
rTTwTbdBpTHJfZZJ
BddPBzwMBzqRqddRGbVShvVhVQvQscvGtV
sSpsHqHMspqMqWsspwsSWsbBPvjrFbddrGTvZLFjdZTZGLLG
NccDncRVNDVJLvLPPJTJGvJL
mRCDNNhgDnghNRQNggNRcNlMtpMPMMtHtShlSSMtlhHW
QrjSFQWzDdCHtpFlbBbVns
PhJwNLfNqgfdLlZHpZJJpptBBb
qmwhfhhfMNWSmSdQCddv
VfRMdbshRmJBqbmDBH
CWwWCWTCrzFpzWwCWFzgppqHDtZBfqDmQtBftBDFqBtq
WlzrWWGWPrpGCGdfSsRGVnGVdNnR
lhLTfppGRhhbZntsbTqMbq
jrHWBHrMgjHPWMgWBJWBWjstPvwFFbbbvtvFqbPtvqws
rBJJJVWjBjLphcMhSVRV
fjrBPBjWVPWPrwtjPpRQZZVdZQddFdHFTZdT
GqlllsGLgMCqGqgTFbmHdTmRzgTm
qHchGscqGClHGhNwhjJJNWpwPB
JzrrJZqLFrnMzVjNNnNnNDwdGHGlHlHbpTZDlmpTHb
gQfQcRWPWgQSStCtfcsPsPmhsGdDhdGDHTwHpDlHwhTG
fvWQgCtfWgtttcPQcPBtjVdBMJMLJBFJMJVzNrJr
cMzNjGGNQFVzNNQVjNdqRLbFDqRpgLRDpDHD
TwtwWJJBJSvmJCWSvTTmTbBpfpRZSfDqqSqDgHLgqdDDqD
vtvmPrtWQMrbhMrG
NqCPqJNJQQQQGCtGPmMTrTpHlNdmpTrwdN
bzhZRDbnZHrmmcwRfM
vWhsnVWWswhSFvDSDsnhbDsLPqqPFjQjgFgtjqqCLJPgQQ
nqpfqfcnclcNcjjQ
BLQJQmLPPvdtTFNjlFNwPs
DgDgLLCQBBmpVSMrgfqnpp
njCnCwwcVCBWjrrhWrHdzJqmhl
QNGptTTQGLTdhqmdJBHT
GtLvDDvLMvppGGVZMssfCBMfcfMf
npPQGpDnsbJhvldphHFfpl
mgqZcqzczzzcqmRzrbrzBvfBLvlhhftFWlhlFtLBvv
cgjmTgbbMgmzqRRwGDDVQVGVSPwTJV
VhPNvgVhbjPsNvsChTZlHtlwZccZMhwlcm
fpznDWDzDfRqffpnrmcRmwlTMZrHTBHB
fWdQLFSnDzpndqzzqgsVvPsJLMsPCgvjPP
RFRDQVvqVMZGBVzqgqPNJNmNhqqPjnPS
rcLLCWrtwlWrWlTbTtlLWrWtjPPgdwgjmNmShpJnjSpSjgSg
LbLTnbbTHsWlfbtZRZGQHHZZDQMVFz
dwcLLSLVdwLdvdfZNJgQZWfffVJQ
CTMlCRCCCTCtBmCFMQJNNNbNfWvQjvZggT
mRnnnpFlvhnlMmBmFMCMCcdHrwzqszprdcwzLDwrSz
JSHLHRMlzJHcGMpwCffZctZmgfqqZm
vnTWvQrnrQjNnBWvnvDnVgqtVWwVgfFmqWfqZFWZ
rdQDBdBrQQhmBNjDTmrTnzPzPPLHSSHzHHRHRLdGLl
GvMRRwGwRFmZRnmbMhZMGcpgZBpdgBJcTsjsBstdds
SNlPzzlPDDQSDDDqfllqDLBpTgWBgWdTpcWjJQsWjjTp
rScrCqPCSLDNrqlFmRVRRrbhmRmFRw
dbtgMNlNSMQPSLNdvVQgSfcHHfJfHJtfmmHTqZffJH
wssswnzwChsrGCCwGCjzCsHFHbzZffbFBcffbHHTBJTZ
rsDRGDwjhWbrbRhGCGLdLNlNQVVDPSlMVMvv
BgPccPPRlZZmTMTZzZTC
jjNjntVtQnWHrJjFPnnqDqJTJTzqJmDDCqChzS
FnQHQjHVNnWVvQpgLPGRdcLpbfLLBl
JLMhFJfHHLJChRvfjLJJnFRpPrpPSrNnrTrTTPntTptrpw
QgcBCqcGBBGzGrNQNSwSrPPTsr
zzWdmzcWcdHCJCRRCF
GSRcjdjGcBnFWbnVLFQR
pCNqTqhDsMsMmNtNCZmMMtdCbVFzbFwnFFnWWFnzVLTQWQLF
qNJpMdCsDNsNNvGPlSPPJjfBBB
lsHjgmFsnFTwHgSPDRSrDqnqrrnr
NmZWcZmzNMZWJbbWvJMJJMzBBBrRrdRfDfppBNqSrrrPBP
JZQZzQtWJhmltVwVCjwGjs
DslBHDpdDlslgffFWnGqHfzH
JNMMCCCCSMvzzGfMzP
hNtCJTwRwZQbwrplpDjlpz
vwvJwLBzwhhwvzwrgwshLwVWWgFfmlSFVRDfWFSVFVfF
mNqbdPnNdpdjnMqSFFMDfSFVMDFRSV
ddpTPTqmbNjjNqndZzvLzJZzHCrrCCzsJH
SLjjlGMVpLpNSTDspsrHpFFwRrZgRfwpfgFZ
nQtWPzbPNQtbdzPtbBCQJNPcwFvZJZFFJrwRwrHcfcfrgF
NQCnqPBWddbPnbCdWdWQnmdVhsMMDsslmSSmMLlVTTDVMm
FZmcqBChfFmfsDjjnNMNjSDgNs
RZwzdvdZRvTRRlvWSgDjStnpntDwNMtD
vHTGRvvvZHlQPRQTbPTVfLJPqcLJBhfmFVJPCF
dStFcccjFjqGFrFHmSHFBjBvzhpprWZpppbppDvzhsvDhT
VMVLNfCCCRTTDtDDDTRz
QLJwMMLnLNVLdtGGgmdScBnB
nTCWnTnrllglrNgNTZFgSZbddHtdHLLwtMLQtfbM
BJGqppPCJVmqqhBJCdwwpLSLHddfHSLHtw
qmzBhczVGsqVBqnFcCjRWNrNlrgD
phrHLNtnMpslNFfwVGwFZSBfFTTz
cmJJDmmbCnCCfBSJGVBwfBfz
DdqdDbcqCPcCQRWmQPqNHhnRMntNNMNhlsLsML
gHHWJWMWsHWgWSnPwVnVNGGDbnwwTl
QjThjhFqqhmQTCVPfDVqPbDVVl
mpFLLrZjjBcmLFmmFtLBJMddMgSdHTscvcJzRHRs
gRdwcCddwghzddzzzsGfZsGnqlqVVhjGDj
DMBNpMDHrNrNLFMmpQJHZGnPjFPFlZjlfGVljGVf
SpbQNmHMzgcRwSSD
drqcMpNbpFpmjzfz
HLGZGsnGLwllzHGGgGnGsBFfmJtmtjfJDSBSJJJB
ZZwQwHTgZnwLGTTnQTHVlgbWCQNhzNcMqbrzcNNQdNcr
TDScznfzNlpbbrtsvjdcbh
BBHqFGWGFmVWqVBBWMtvCLvsLdvrvjLjdLbsvm
tPZHGFJPJqVwMWHJVRRSZNfQnzfpnTpNfl
FWNZgWCngsNwJwlQlrRTRhSjSS
GGLcVVcVmppMmpTjTRHlbRbSrVBh
rvmdzPcdzmzMrCNNPJFntFsCtD
MtfLBzSLmMtfBMQzMmzmSlfdTDvGCZGCndZnZgWDwGCZ
HhqrrpppcqhdbjPvbgGvTCnWDbTWZT
cNjsdqPqchJBlmzlVQLtBJ
DwwVFZlDBsZFDvLPdpjLjSVHjpLc
nMnztWhhfPSffcddGpgp
tQnrQzhzNtzbNrBwPJwTslTvNFFP
LWMvHJJrJwtzvgwMwVdGfcpNfdDVDWfdBB
jZPFmjnbmhPfTVfVHdhTTV
qqQCmCmbqCQqjQsQvrQSHSJrzz
wNzmDRwmgcGphZcPvLLZHjjFLF
JlbsClVVqDqFZjJD
WSlnCbttftsCsWftbCCrTffbpdzMwgMgSpRmdwdRzggmDGGg
gCCRBClgfCgFFTltTGgBqTsQhzLzQQNPnvrNzHrrfPzHLr
DMjqWSVwDwDwZDHZNvLQnrnrPrNv
bcmWJqdVcbtgBglbGTCl
SFDcrFHtlqhqqLdzTTwdJLPNDL
vBWsWvsmgvvvdPwNnn
smfRbpsWMBmsmMsBBBNbtSFttjCHSScbhHtHhHjb
SQpgGgMNvggQGMvQcgnHWmldnHWTWndnSHHF
DwbDPzthtttljTzTFBlmzl
DstCswftDbZbCChPPRrfwsfPQlLccJQLvVGNGNVpMNvZcvgG
HdqfjjLfHqFSHddVWNBjsWhWRRJtBNBs
gPMQHpmrcmnbRQNRRJsWttWW
pmbcZwbrPPrnTPMFFdDwqHwvHDvzDq
FFsVtFGVGvWVhlfVhzlsFvHbPwPmwHLTSbLjcLtbSbLm
rZrpJwCqnnJHmqcbcTLTbS
RCZZQMQpzvRhswVg';

//Part 1
$group_array = explode(PHP_EOL, $string);

function check_priority($char) {
    foreach (range('a', 'z') as $key => $letter) {
        if($char == $letter) {
            return $key + 1;
        }
    }

    foreach (range('A', 'Z') as $key => $letter) {
        if($char == $letter) {
            return $key + 27;
        }
    }
}

$sum = 0;
foreach ($group_array as $row) {
    $middle = floor(strlen($row) / 2);
    $half_1 = substr($row, 0, $middle);
    $half_2 = substr($row, $middle);

    $array_1 = str_split($half_1);
    $array_2 = str_split($half_2);

    $char = array_merge(array_intersect($array_1, $array_2));
    $sum = $sum + check_priority($char[0]);
}

echo 'Sum 1: ' . $sum;
echo '<br>';

//Part 2
$sum = 0;
$group_array_new = array_chunk($group_array, 3);
foreach ($group_array_new as $row) {
    
    $rucksacks_1 = $row[0] ? str_split($row[0]) : array();
    $rucksacks_2 = $row[1] ? str_split($row[1]) : array();
    $rucksacks_3 = $row[2] ? str_split($row[2]) : array();
    $char = array_merge(array_intersect($rucksacks_1, $rucksacks_2, $rucksacks_3));

    $char = array_merge(array_intersect($rucksacks_1, $rucksacks_2, $rucksacks_3));
    $sum = $sum + check_priority($char[0]);
}
echo 'Sum 2: ' . $sum;

@include('templates/footer.php');
